# This is the default configuration, using a non-persistent in-memory database.
# *** IT WILL NOT SAVE YOUR DATA ACROSS SERVER RESTARTS ***
datasource-config: db-h2.properties

# Configure a _real_ data source, either a persistent file H2 or external database
#datasource-config: db-mysql.properties
#datasource-config: db-test.properties

h2:
  # Start the H2 local database
  enable: true
  # Allow access through the web client
  # http://localhost:8082/
  web.enable: false
  # Allow access through a DB client
  # jdbc:h2:tcp://localhost/mem:test
  # jdbc:h2:mem:test;MODE=MYSQL
  tcp.enable: false
