package com.briarcraft.rtw.change.block

const val TYPE_BREAK = "BREAK"
const val TYPE_IGNITE = "IGNITE"
const val TYPE_BURN = "BURN"
const val TYPE_GROW = "GROW"
const val TYPE_SPREAD = "SPREAD"
const val TYPE_FORM = "FORM"
const val TYPE_FADE = "FADE"
const val TYPE_EXPLODE = "EXPLODE"
const val TYPE_PISTON = "PISTON"
const val TYPE_PLACE = "PLACE"
const val TYPE_ABSORB = "ABSORB"
const val TYPE_BUCKET = "BUCKET"
const val TYPE_PORTAL = "PORTAL"
const val TYPE_FERTILIZE = "FERTILIZE"
const val TYPE_FLOW = "FLOW"
const val TYPE_PHYSICS = "PHYSICS"
const val TYPE_MOVE = "MOVE"
const val TYPE_EAT = "EAT"
const val TYPE_TAKE = "TAKE"
const val TYPE_USE = "USE"
const val TYPE_FALL = "FALL"
const val TYPE_CHANGE = "CHANGE"
const val TYPE_INFEST = "INFEST"
