package com.briarcraft.econ.recipe

import com.briarcraft.econ.api.recipe.RecipeManager
import com.briarcraft.econ.api.recipe.RecipeSet
import org.bukkit.NamespacedKey

// TODO This is a duplicate of the configuration
class RemovedRecipes(recipeManager: RecipeManager): RecipeSet {
    override val recipes = setOf(
        "minecraft:iron_ingot_from_iron_block",
        "minecraft:gold_ingot_from_gold_block",
        "minecraft:copper_ingot_from_waxed_copper_block",
        "minecraft:netherite_ingot_from_netherite_block",
        "minecraft:gold_nugget_from_smelting",
        "minecraft:iron_nugget_from_smelting",
        "minecraft:gold_nugget_from_blasting",
        "minecraft:iron_nugget_from_blasting",
        "minecraft:bone_meal_from_bone_block",

        "minecraft:slime_ball",
        "minecraft:wheat",
        "minecraft:honey_bottle",

        "minecraft:raw_copper",
        "minecraft:raw_iron",
        "minecraft:raw_gold",
        "minecraft:redstone",
        "minecraft:coal",
        "minecraft:lapis_lazuli",
        "minecraft:dried_kelp",
        "minecraft:copper_ingot",
        "minecraft:diamond",
        "minecraft:emerald",
        "minecraft:map_extending",

        "minecraft:sugar_from_honey_bottle",
        "minecraft:black_dye_from_wither_rose",
        "minecraft:light_blue_dye_from_blue_white_dye",
        "minecraft:stick_from_bamboo_item",
        "minecraft:blue_dye",
        "minecraft:red_dye_from_beetroot",

        "minecraft:mossy_cobblestone_from_moss_block",
        "minecraft:mossy_stone_bricks_from_moss_block",

        "minecraft:dye_black_bed",
        "minecraft:dye_black_carpet",
        "minecraft:dye_black_wool",
        "minecraft:dye_blue_bed",
        "minecraft:dye_blue_carpet",
        "minecraft:dye_blue_wool",
        "minecraft:dye_brown_bed",
        "minecraft:dye_brown_carpet",
        "minecraft:dye_brown_wool",
        "minecraft:dye_cyan_bed",
        "minecraft:dye_cyan_carpet",
        "minecraft:dye_cyan_wool",
        "minecraft:dye_gray_bed",
        "minecraft:dye_gray_carpet",
        "minecraft:dye_gray_wool",
        "minecraft:dye_green_bed",
        "minecraft:dye_green_carpet",
        "minecraft:dye_green_wool",
        "minecraft:dye_light_blue_bed",
        "minecraft:dye_light_blue_carpet",
        "minecraft:dye_light_blue_wool",
        "minecraft:dye_light_gray_bed",
        "minecraft:dye_light_gray_carpet",
        "minecraft:dye_light_gray_wool",
        "minecraft:dye_lime_bed",
        "minecraft:dye_lime_carpet",
        "minecraft:dye_lime_wool",
        "minecraft:dye_magenta_bed",
        "minecraft:dye_magenta_carpet",
        "minecraft:dye_magenta_wool",
        "minecraft:dye_orange_bed",
        "minecraft:dye_orange_carpet",
        "minecraft:dye_orange_wool",
        "minecraft:dye_pink_bed",
        "minecraft:dye_pink_carpet",
        "minecraft:dye_pink_wool",
        "minecraft:dye_purple_bed",
        "minecraft:dye_purple_carpet",
        "minecraft:dye_purple_wool",
        "minecraft:dye_red_bed",
        "minecraft:dye_red_carpet",
        "minecraft:dye_red_wool",
        "minecraft:dye_white_bed",
        "minecraft:dye_white_carpet",
        "minecraft:dye_white_wool",
        "minecraft:dye_yellow_bed",
        "minecraft:dye_yellow_carpet",
        "minecraft:dye_yellow_wool",

        "minecraft:coast_armor_trim_smithing_template",
        "minecraft:dune_armor_trim_smithing_template",
        "minecraft:eye_armor_trim_smithing_template",
        "minecraft:host_armor_trim_smithing_template",
        "minecraft:netherite_upgrade_smithing_template",
        "minecraft:raiser_armor_trim_smithing_template",
        "minecraft:rib_armor_trim_smithing_template",
        "minecraft:sentry_armor_trim_smithing_template",
        "minecraft:shaper_armor_trim_smithing_template",
        "minecraft:silence_armor_trim_smithing_template",
        "minecraft:snout_armor_trim_smithing_template",
        "minecraft:spire_armor_trim_smithing_template",
        "minecraft:tide_armor_trim_smithing_template",
        "minecraft:ward_armor_trim_smithing_template",
        "minecraft:wayfinder_armor_trim_smithing_template",
        "minecraft:wild_armor_trim_smithing_template",
        "minecraft:vex_armor_trim_smithing_template",

        "minecraft:coast_armor_trim_smithing_template_smithing_trim",
        "minecraft:dune_armor_trim_smithing_template_smithing_trim",
        "minecraft:eye_armor_trim_smithing_template_smithing_trim",
        "minecraft:host_armor_trim_smithing_template_smithing_trim",
        "minecraft:netherite_upgrade_smithing_template_smithing_trim",
        "minecraft:raiser_armor_trim_smithing_template_smithing_trim",
        "minecraft:rib_armor_trim_smithing_template_smithing_trim",
        "minecraft:sentry_armor_trim_smithing_template_smithing_trim",
        "minecraft:shaper_armor_trim_smithing_template_smithing_trim",
        "minecraft:silence_armor_trim_smithing_template_smithing_trim",
        "minecraft:snout_armor_trim_smithing_template_smithing_trim",
        "minecraft:spire_armor_trim_smithing_template_smithing_trim",
        "minecraft:tide_armor_trim_smithing_template_smithing_trim",
        "minecraft:ward_armor_trim_smithing_template_smithing_trim",
        "minecraft:wayfinder_armor_trim_smithing_template_smithing_trim",
        "minecraft:wild_armor_trim_smithing_template_smithing_trim",
        "minecraft:vex_armor_trim_smithing_template_smithing_trim",
    )
        .map(NamespacedKey::fromString)
        .mapNotNull { recipeManager.getRecipe(it!!) }
        .toSet()
}